
set(ENV{PKG_CONFIG_PATH} "/Users/afalls/code/game-shell-sdk/pkgconf/ClockworkOS/0.5")
find_package(PkgConfig REQUIRED)

pkg_check_modules(QT5PRINTSUPPORT REQUIRED Qt5PrintSupport)

add_library(QT5PRINTSUPPORT INTERFACE IMPORTED)
set_target_properties(QT5PRINTSUPPORT PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                      "${QT5PRINTSUPPORT_INCLUDE_DIRS}")
set_target_properties(QT5PRINTSUPPORT PROPERTIES INTERFACE_LINK_DIRECTORIES
                      "${QT5PRINTSUPPORT_LIBRARY_DIRS}")
set_target_properties(QT5PRINTSUPPORT PROPERTIES INTERFACE_LINK_LIBRARIES
                      "${QT5PRINTSUPPORT_LIB_LIBRARIES}")
set_target_properties(QT5PRINTSUPPORT PROPERTIES INTERFACE_COMPILE_OPTIONS
                      "${QT5PRINTSUPPORT_CFLAGS_OTHER}")
