
set(ENV{PKG_CONFIG_PATH} "/Users/afalls/code/game-shell-sdk/pkgconf/ClockworkOS/0.5")
find_package(PkgConfig REQUIRED)

pkg_check_modules(QT5OPENGLEXTENSIONS REQUIRED Qt5OpenGLExtensions)

add_library(QT5OPENGLEXTENSIONS INTERFACE IMPORTED)
set_target_properties(QT5OPENGLEXTENSIONS PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                      "${QT5OPENGLEXTENSIONS_INCLUDE_DIRS}")
set_target_properties(QT5OPENGLEXTENSIONS PROPERTIES INTERFACE_LINK_DIRECTORIES
                      "${QT5OPENGLEXTENSIONS_LIBRARY_DIRS}")
set_target_properties(QT5OPENGLEXTENSIONS PROPERTIES INTERFACE_LINK_LIBRARIES
                      "${QT5OPENGLEXTENSIONS_LIB_LIBRARIES}")
set_target_properties(QT5OPENGLEXTENSIONS PROPERTIES INTERFACE_COMPILE_OPTIONS
                      "${QT5OPENGLEXTENSIONS_CFLAGS_OTHER}")
