
set(ENV{PKG_CONFIG_PATH} "/Users/afalls/code/game-shell-sdk/pkgconf/ClockworkOS/0.5")
find_package(PkgConfig REQUIRED)

pkg_check_modules(WAYLAND_PROTOCOLS REQUIRED wayland-protocols)

add_library(WAYLAND_PROTOCOLS INTERFACE IMPORTED)
set_target_properties(WAYLAND_PROTOCOLS PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                      "${WAYLAND_PROTOCOLS_INCLUDE_DIRS}")
set_target_properties(WAYLAND_PROTOCOLS PROPERTIES INTERFACE_LINK_DIRECTORIES
                      "${WAYLAND_PROTOCOLS_LIBRARY_DIRS}")
set_target_properties(WAYLAND_PROTOCOLS PROPERTIES INTERFACE_LINK_LIBRARIES
                      "${WAYLAND_PROTOCOLS_LIB_LIBRARIES}")
set_target_properties(WAYLAND_PROTOCOLS PROPERTIES INTERFACE_COMPILE_OPTIONS
                      "${WAYLAND_PROTOCOLS_CFLAGS_OTHER}")
