
set(ENV{PKG_CONFIG_PATH} "/Users/afalls/code/game-shell-sdk/pkgconf/ClockworkOS/0.5")
find_package(PkgConfig REQUIRED)

pkg_check_modules(LIBDRM_FREEDRENO REQUIRED libdrm_freedreno)

add_library(LIBDRM_FREEDRENO INTERFACE IMPORTED)
set_target_properties(LIBDRM_FREEDRENO PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                      "${LIBDRM_FREEDRENO_INCLUDE_DIRS}")
set_target_properties(LIBDRM_FREEDRENO PROPERTIES INTERFACE_LINK_DIRECTORIES
                      "${LIBDRM_FREEDRENO_LIBRARY_DIRS}")
set_target_properties(LIBDRM_FREEDRENO PROPERTIES INTERFACE_LINK_LIBRARIES
                      "${LIBDRM_FREEDRENO_LIB_LIBRARIES}")
set_target_properties(LIBDRM_FREEDRENO PROPERTIES INTERFACE_COMPILE_OPTIONS
                      "${LIBDRM_FREEDRENO_CFLAGS_OTHER}")
