
set(ENV{PKG_CONFIG_PATH} "/Users/afalls/code/game-shell-sdk/pkgconf/ClockworkOS/0.5")
find_package(PkgConfig REQUIRED)

pkg_check_modules(XF86VIDMODEPROTO REQUIRED xf86vidmodeproto)

add_library(XF86VIDMODEPROTO INTERFACE IMPORTED)
set_target_properties(XF86VIDMODEPROTO PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                      "${XF86VIDMODEPROTO_INCLUDE_DIRS}")
set_target_properties(XF86VIDMODEPROTO PROPERTIES INTERFACE_LINK_DIRECTORIES
                      "${XF86VIDMODEPROTO_LIBRARY_DIRS}")
set_target_properties(XF86VIDMODEPROTO PROPERTIES INTERFACE_LINK_LIBRARIES
                      "${XF86VIDMODEPROTO_LIB_LIBRARIES}")
set_target_properties(XF86VIDMODEPROTO PROPERTIES INTERFACE_COMPILE_OPTIONS
                      "${XF86VIDMODEPROTO_CFLAGS_OTHER}")
