
set(ENV{PKG_CONFIG_PATH} "/Users/afalls/code/game-shell-sdk/pkgconf/ClockworkOS/0.5")
find_package(PkgConfig REQUIRED)

pkg_check_modules(LIBPULSE_MAINLOOP_GLIB REQUIRED libpulse-mainloop-glib)

add_library(LIBPULSE_MAINLOOP_GLIB INTERFACE IMPORTED)
set_target_properties(LIBPULSE_MAINLOOP_GLIB PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                      "${LIBPULSE_MAINLOOP_GLIB_INCLUDE_DIRS}")
set_target_properties(LIBPULSE_MAINLOOP_GLIB PROPERTIES INTERFACE_LINK_DIRECTORIES
                      "${LIBPULSE_MAINLOOP_GLIB_LIBRARY_DIRS}")
set_target_properties(LIBPULSE_MAINLOOP_GLIB PROPERTIES INTERFACE_LINK_LIBRARIES
                      "${LIBPULSE_MAINLOOP_GLIB_LIB_LIBRARIES}")
set_target_properties(LIBPULSE_MAINLOOP_GLIB PROPERTIES INTERFACE_COMPILE_OPTIONS
                      "${LIBPULSE_MAINLOOP_GLIB_CFLAGS_OTHER}")
