
set(ENV{PKG_CONFIG_PATH} "/Users/afalls/code/game-shell-sdk/pkgconf/ClockworkOS/0.5")
find_package(PkgConfig REQUIRED)

pkg_check_modules(SCRNSAVERPROTO REQUIRED scrnsaverproto)

add_library(SCRNSAVERPROTO INTERFACE IMPORTED)
set_target_properties(SCRNSAVERPROTO PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                      "${SCRNSAVERPROTO_INCLUDE_DIRS}")
set_target_properties(SCRNSAVERPROTO PROPERTIES INTERFACE_LINK_DIRECTORIES
                      "${SCRNSAVERPROTO_LIBRARY_DIRS}")
set_target_properties(SCRNSAVERPROTO PROPERTIES INTERFACE_LINK_LIBRARIES
                      "${SCRNSAVERPROTO_LIB_LIBRARIES}")
set_target_properties(SCRNSAVERPROTO PROPERTIES INTERFACE_COMPILE_OPTIONS
                      "${SCRNSAVERPROTO_CFLAGS_OTHER}")
