
set(ENV{PKG_CONFIG_PATH} "/Users/afalls/code/game-shell-sdk/pkgconf/ClockworkOS/0.5")
find_package(PkgConfig REQUIRED)

pkg_check_modules(LIBMPEG2CONVERT REQUIRED libmpeg2convert)

add_library(LIBMPEG2CONVERT INTERFACE IMPORTED)
set_target_properties(LIBMPEG2CONVERT PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                      "${LIBMPEG2CONVERT_INCLUDE_DIRS}")
set_target_properties(LIBMPEG2CONVERT PROPERTIES INTERFACE_LINK_DIRECTORIES
                      "${LIBMPEG2CONVERT_LIBRARY_DIRS}")
set_target_properties(LIBMPEG2CONVERT PROPERTIES INTERFACE_LINK_LIBRARIES
                      "${LIBMPEG2CONVERT_LIB_LIBRARIES}")
set_target_properties(LIBMPEG2CONVERT PROPERTIES INTERFACE_COMPILE_OPTIONS
                      "${LIBMPEG2CONVERT_CFLAGS_OTHER}")
